-- ============================================================================
-- ACLED LOCATIONS TABLE
-- ============================================================================
-- This table stores unique combinations of admin1, admin2, admin3
-- (State/Region, District, Township) from ACLED data for reference and mapping.

CREATE TABLE IF NOT EXISTS acled_locations (
    location_id SERIAL PRIMARY KEY,
    admin1 VARCHAR(100),  -- State/Region
    admin2 VARCHAR(100),  -- District
    admin3 VARCHAR(100),  -- Township
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(admin1, admin2, admin3)
);

COMMENT ON TABLE acled_locations IS 'Reference table for ACLED administrative location combinations';
COMMENT ON COLUMN acled_locations.admin1 IS 'State or Region (admin level 1)';
COMMENT ON COLUMN acled_locations.admin2 IS 'District (admin level 2)';
COMMENT ON COLUMN acled_locations.admin3 IS 'Township (admin level 3)';

-- Insert unique location combinations
-- Using ON CONFLICT DO NOTHING to skip duplicates on updates
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Hinthada', 'Hinthada') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Hinthada', 'Ingapu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Hinthada', 'Kyangin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Hinthada', 'Lemyethna') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Hinthada', 'Myanaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Hinthada', 'Zalun') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Labutta', 'Labutta') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Labutta', 'Mawlamyinegyun') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Maubin', 'Danubyu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Maubin', 'Maubin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Maubin', 'Nyaungdon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Maubin', 'Pantanaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Myaungmya', 'Einme') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Myaungmya', 'Myaungmya') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Myaungmya', 'Wakema') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pathein', 'Kangyidaunt') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pathein', 'Kyaunggon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pathein', 'Kyonpyaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pathein', 'Ngapudaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pathein', 'Pathein') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pathein', 'Thabaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pathein', 'Yegyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pyapon', 'Bogale') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pyapon', 'Dedaye') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pyapon', 'Kyaiklat') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Ayeyarwady', 'Pyapon', 'Pyapon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Bago', 'Bago') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Bago', 'Daik-U') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Bago', 'Kawa') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Bago', 'Kyauktaga') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Bago', 'Nyaunglebin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Bago', 'Shwegyin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Bago', 'Thanatpin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Bago', 'Waw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Taungoo', 'Htantabin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Taungoo', 'Kyaukkyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Taungoo', 'Oktwin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Taungoo', 'Phyu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Taungoo', 'Taungoo') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-East', 'Taungoo', 'Yedashe') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Pyay', 'Padaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Pyay', 'Paukkhaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Pyay', 'Paungde') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Pyay', 'Pyay') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Pyay', 'Shwedaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Pyay', 'Thegon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Thayarwady', 'Gyobingauk') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Thayarwady', 'Letpadan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Thayarwady', 'Minhla') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Thayarwady', 'Monyo') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Thayarwady', 'Nattalin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Thayarwady', 'Okpho') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Thayarwady', 'Thayarwady') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Bago-West', 'Thayarwady', 'Zigon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Chin', 'Falam', 'Falam') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Chin', 'Falam', 'Tedim') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Chin', 'Falam', 'Tonzang') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Chin', 'Hakha', 'Hakha') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Chin', 'Hakha', 'Thantlang') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Chin', 'Matupi', 'Matupi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Chin', 'Matupi', 'Paletwa') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Chin', 'Mindat', 'Kanpetlet') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Chin', 'Mindat', 'Mindat') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Bhamo', 'Bhamo') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Bhamo', 'Mansi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Bhamo', 'Momauk') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Bhamo', 'Shwegu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Mohnyin', 'Hpakant') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Mohnyin', 'Mogaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Mohnyin', 'Mohnyin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Myitkyina', 'Chipwi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Myitkyina', 'Injangyang') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Myitkyina', 'Myitkyina') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Myitkyina', 'Tanai') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Myitkyina', 'Tsawlaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Myitkyina', 'Waingmaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Puta-O', 'Khaunglanhpu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Puta-O', 'Machanbaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Puta-O', 'Nawngmun') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Puta-O', 'Puta-O') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kachin', 'Puta-O', 'Sumprabum') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayah', 'Bawlake', 'Bawlake') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayah', 'Bawlake', 'Hpasawng') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayah', 'Bawlake', 'Mese') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayah', 'Loikaw', 'Demoso') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayah', 'Loikaw', 'Hpruso') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayah', 'Loikaw', 'Loikaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayah', 'Loikaw', 'Shadaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayin', 'Hpa-An', 'Hlaingbwe') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayin', 'Hpa-An', 'Hpa-An') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayin', 'Hpa-An', 'Thandaunggyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayin', 'Hpapun', 'Hpapun') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayin', 'Kawkareik', 'Kawkareik') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayin', 'Kawkareik', 'Kyainseikgyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Kayin', 'Myawaddy', 'Myawaddy') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Gangaw', 'Gangaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Gangaw', 'Saw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Gangaw', 'Tilin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Magway', 'Chauk') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Magway', 'Magway') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Magway', 'Myothit') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Magway', 'Natmauk') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Magway', 'Taungdwingyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Magway', 'Yenangyaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Minbu', 'Minbu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Minbu', 'Ngape') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Minbu', 'Pwintbyu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Minbu', 'Salin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Minbu', 'Sidoktaya') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Pakokku', 'Myaing') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Pakokku', 'Pakokku') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Pakokku', 'Pauk') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Pakokku', 'Seikphyu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Pakokku', 'Yesagyo') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Thayet', 'Aunglan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Thayet', 'Kamma') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Thayet', 'Mindon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Thayet', 'Minhla') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Thayet', 'Sinbaungwe') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Magway', 'Thayet', 'Thayet') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Kyaukse', 'Kyaukse') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Kyaukse', 'Myittha') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Kyaukse', 'Sintgaing') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Kyaukse', 'Tada-U') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Mandalay', 'Amarapura') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Mandalay', 'Aungmyaythazan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Mandalay', 'Chanayethazan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Mandalay', 'Chanmyathazi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Mandalay', 'Mahaaungmyay') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Mandalay', 'Patheingyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Mandalay', 'Pyigyitagon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Mandalay', NULL) ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Meiktila', 'Mahlaing') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Meiktila', 'Meiktila') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Meiktila', 'Thazi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Meiktila', 'Wundwin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Myingyan', 'Myingyan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Myingyan', 'Natogyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Myingyan', 'Ngazun') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Myingyan', 'Taungtha') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Nyaung-U', 'Kyaukpadaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Nyaung-U', 'Nyaung-U') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Pyinoolwin', 'Madaya') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Pyinoolwin', 'Mogoke') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Pyinoolwin', 'Pyinoolwin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Pyinoolwin', 'Singu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Pyinoolwin', 'Thabeikkyin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Yamethin', 'Pyawbwe') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mandalay', 'Yamethin', 'Yamethin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mon', 'Mawlamyine', 'Chaungzon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mon', 'Mawlamyine', 'Kyaikmaraw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mon', 'Mawlamyine', 'Mawlamyine') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mon', 'Mawlamyine', 'Mudon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mon', 'Mawlamyine', 'Thanbyuzayat') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mon', 'Mawlamyine', 'Ye') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mon', 'Thaton', 'Bilin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mon', 'Thaton', 'Kyaikto') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mon', 'Thaton', 'Paung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Mon', 'Thaton', 'Thaton') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Nay Pyi Taw', 'Det Khi Na', 'Det Khi Na Thi Ri') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Nay Pyi Taw', 'Det Khi Na', 'Lewe') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Nay Pyi Taw', 'Det Khi Na', 'Pyinmana') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Nay Pyi Taw', 'Det Khi Na', 'Za Bu Thi Ri') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Nay Pyi Taw', 'Nay Pyi Taw', NULL) ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Nay Pyi Taw', 'Oke Ta Ra', 'Oke Ta Ra Thi Ri') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Nay Pyi Taw', 'Oke Ta Ra', 'Poke Ba Thi Ri') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Nay Pyi Taw', 'Oke Ta Ra', 'Tatkon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Nay Pyi Taw', 'Oke Ta Ra', 'Zay Yar Thi Ri') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Kyaukpyu', 'Ann') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Kyaukpyu', 'Kyaukpyu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Kyaukpyu', 'Munaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Kyaukpyu', 'Ramree') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Maungdaw', 'Buthidaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Maungdaw', 'Maungdaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Mrauk-U', 'Kyauktaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Mrauk-U', 'Minbya') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Mrauk-U', 'Mrauk-U') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Mrauk-U', 'Myebon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Sittwe', 'Pauktaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Sittwe', 'Ponnagyun') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Sittwe', 'Rathedaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Sittwe', 'Sittwe') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Thandwe', 'Gwa') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Thandwe', 'Thandwe') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Rakhine', 'Thandwe', 'Toungup') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Hkamti', 'Hkamti') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Hkamti', 'Homalin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Kale', 'Kale') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Kale', 'Kalewa') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Kale', 'Mingin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Kanbalu', 'Kanbalu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Kanbalu', 'Kyunhla') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Katha', 'Banmauk') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Katha', 'Indaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Katha', 'Katha') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Katha', 'Tigyaing') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Kawlin', 'Kawlin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Kawlin', 'Pinlebu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Kawlin', 'Wuntho') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Mawlaik', 'Mawlaik') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Mawlaik', 'Paungbyin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Monywa', 'Ayadaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Monywa', 'Budalin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Monywa', 'Chaung-U') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Monywa', 'Monywa') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Naga Self-Administered Zone', 'Lahe') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Naga Self-Administered Zone', 'Lay Shi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Naga Self-Administered Zone', 'Nanyun') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Sagaing', 'Myaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Sagaing', 'Myinmu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Sagaing', 'Sagaing') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Shwebo', 'Khin-U') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Shwebo', 'Shwebo') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Shwebo', 'Tabayin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Shwebo', 'Taze') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Shwebo', 'Wetlet') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Shwebo', 'Ye-U') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Tamu', 'Tamu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Yinmarbin', 'Kani') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Yinmarbin', 'Pale') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Yinmarbin', 'Salingyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Sagaing', 'Yinmarbin', 'Yinmarbin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-East', 'Kengtung', 'Kengtung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-East', 'Kengtung', 'Mongkhet') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-East', 'Kengtung', 'Mongla') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-East', 'Kengtung', 'Mongping') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-East', 'Kengtung', 'Mongyang') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-East', 'Monghsat', 'Monghsat') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-East', 'Monghsat', 'Mongton') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-East', 'Tachileik', 'Monghpyak') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-East', 'Tachileik', 'Mongyawng') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-East', 'Tachileik', 'Tachileik') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Hopang', 'Hopang') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Kokang Self-Administered Zone', 'Konkyan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Kokang Self-Administered Zone', 'Laukkaing') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Kyaukme', 'Hsipaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Kyaukme', 'Kyaukme') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Kyaukme', 'Namtu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Kyaukme', 'Nawnghkio') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Lashio', 'Hseni') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Lashio', 'Kunlong') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Lashio', 'Lashio') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Lashio', 'Mongyai') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Lashio', 'Tangyan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Matman', 'Matman') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Matman', 'Pangsang') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Mongmit', 'Mabein') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Mongmit', 'Mongmit') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Muse', 'Kutkai') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Muse', 'Muse') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Muse', 'Namhkan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Pa Laung Self-Administered Zone', 'Manton') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-North', 'Pa Laung Self-Administered Zone', 'Namhsan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Danu Self-Administered Zone', 'Pindaya') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Danu Self-Administered Zone', 'Ywangan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Langkho', 'Langkho') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Langkho', 'Mawkmai') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Langkho', 'Mongnai') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Langkho', 'Mongpan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Loilen', 'Kunhing') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Loilen', 'Kyethi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Loilen', 'Laihka') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Loilen', 'Loilen') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Loilen', 'Monghsu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Loilen', 'Mongkaing') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Loilen', 'Nansang') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Pa-O Self-Administered Zone', 'Hopong') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Pa-O Self-Administered Zone', 'Hsihseng') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Pa-O Self-Administered Zone', 'Pinlaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Taunggyi', 'Kalaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Taunggyi', 'Lawksawk') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Taunggyi', 'Nyaungshwe') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Taunggyi', 'Pekon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Shan-South', 'Taunggyi', 'Taunggyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Tanintharyi', 'Dawei', 'Dawei') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Tanintharyi', 'Dawei', 'Launglon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Tanintharyi', 'Dawei', 'Thayetchaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Tanintharyi', 'Dawei', 'Yebyu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Tanintharyi', 'Kawthoung', 'Bokpyin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Tanintharyi', 'Kawthoung', 'Kawthoung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Tanintharyi', 'Myeik', 'Kyunsu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Tanintharyi', 'Myeik', 'Myeik') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Tanintharyi', 'Myeik', 'Palaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Tanintharyi', 'Myeik', 'Tanintharyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon', NULL) ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Botahtaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Dagon Myothit-East') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Dagon Myothit-North') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Dagon Myothit-Seikkan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Dagon Myothit-South') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Dawbon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Mingalartaungnyunt') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'North Okkalapa') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Pazundaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'South Okkalapa') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Tamwe') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Thaketa') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Thingangyun') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-East', 'Yankin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-North', 'Hlaingtharya-East') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-North', 'Hlaingtharya-West') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-North', 'Hlegu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-North', 'Hmawbi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-North', 'Htantabin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-North', 'Insein') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-North', 'Mingaladon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-North', 'Shwepyithar') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-North', 'Taikkyi') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-South', 'Dala') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-South', 'Kawhmu') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-South', 'Kayan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-South', 'Kungyangon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-South', 'Kyauktan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-South', 'Seikgyikanaungto') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-South', 'Thanlyin') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-South', 'Thongwa') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-South', 'Twantay') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Ahlone') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Bahan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Dagon') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Hlaing') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Kamaryut') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Kyauktada') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Kyeemyindaing') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Lanmadaw') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Latha') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Mayangone') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Pabedan') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;
INSERT INTO acled_locations (admin1, admin2, admin3) VALUES ('Yangon', 'Yangon-West', 'Sanchaung') ON CONFLICT (admin1, admin2, admin3) DO NOTHING;

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_acled_locations_admin1 ON acled_locations(admin1);
CREATE INDEX IF NOT EXISTS idx_acled_locations_admin2 ON acled_locations(admin2);
CREATE INDEX IF NOT EXISTS idx_acled_locations_admin3 ON acled_locations(admin3);